### ISSUE TITLE
Prospects - date de conversion

### ISSUE THREAD

**Issue by SandraGAZZA** [B3Software/scx.upnbiz.com#637]
@mariefranceupnbiz @MichaelAntoine 

Marie merci de compléter ce ticket
Les listes ci jointes sont une extraction des prospects de SCC et SCP
Pour Durand guillaume et Plaisance JB une date de conversion au 07/01/2015 apparait ce qui n'aurait pas été généré par @mariefranceupnbiz @maryleneupnbiz 

Il faut trouver le pourquoi car en cas de mailing ou relance de prospects aux prospects, cela évitera certains oublis ou couac

![capture d ecran 2015-02-24 a 08 57 23](https://cloud.githubusercontent.com/assets/2931522/6345195/494423e0-bc03-11e4-9922-4437df9097dd.png)
![capture d ecran 2015-02-24 a 08 57 55](https://cloud.githubusercontent.com/assets/2931522/6345196/49470268-bc03-11e4-9bf7-8b02d97e79b3.png)

**Comment by MichaelAntoine** [comment]
@SandraGAZZA  pour info : https://si-upnbiz.atlassian.net/browse/SCSECURE-635

**Comment by MichaelAntoine** [comment]
@SandraGAZZA possible d'avoir une extraction numérique ?

**Comment by mariefranceupnbiz** [comment]
En faisant une extraction Prospects Portés, je me suis apperçue que ces deux P.P apparaissaient avec une date de conversion sans que cela été fait par mes soins ni par Marylène. Du coup ils n'apparaissent même plus dans les Prospects Portés !!!

**Comment by cyrilcaturani** [comment]
@SandraGAZZA @MichaelAntoine @mariefranceupnbiz @maryleneupnbiz 
J'ai l'impression que les prospects SCX remontent sur WP
Je suis en train de regarder si c'est voulu ou pas dans les différents tickets relatifs aux prospects

Ca viendrait de la la conversion je pense, car lors d'une conversion via WP  l'utilisateur qui le fait ne peut être authentifié (login unique sur wpadmin)  contrairement à SCX ou chaque modification/conversion/suppression/creation de prospect est authentifié

**Comment by cyrilcaturani** [comment]
@SandraGAZZA @MichaelAntoine @mariefranceupnbiz @maryleneupnbiz 

Pour Plaisance jean baptiste : Je pense que c'est lié au fait qu'il soit porté chez webportage avec le meme email/nom/prénom, du coup il a du etre associé depuis wpadmin (lié au problème de la remontée des prospects scx dans wpadmin), date d'inscription porté 2012-02-11

Pour guillaume durand, là condition de recherche des portés associables est nom/prenom et/ou email
Un porté existant sour le nom de guillaume durand, sur webportage, ce problème est surement du à la même chose que le porté plaisance.


**actions à mener**
- @maryleneupnbiz @mariefranceupnbiz @SandraGAZZA 
   - Qu'est ce que je fais de plaisance jeanbaptiste (prospect)?
   Il est porté chez webportage, a facturé fin 2014 sur webportage, dois je le laissé associé (le prospect  scx) à ce porté (webportage) ? ou le dissocier ?
   - Guillaume durand, à priori je devrais le dissocier, mais je préfère avoir confirmation

- @cyrilcaturani @MichaelAntoine 
   - Isoler les prospects par marque (en fait côté wpadmin)
   - faire une requete pour ressortir les prospects scx concernés par une conversion via wpadmin

**Comment by cyrilcaturani** [comment]
@MichaelAntoine 
pour info : https://si-upnbiz.atlassian.net/browse/WPSECURE-939, https://si-upnbiz.atlassian.net/browse/UNBAPI-60, https://si-upnbiz.atlassian.net/browse/SCSECURE-635

**Comment by MichaelAntoine** [comment]
@SandraGAZZA  un petit up

**Comment by SandraGAZZA** [comment]
Commenté dans Atlassian :

vu avec Sandra Gazza
Il ne faut pas associer un prospect à un porté s'il ne sont pas sur la mm marque
exemple :

    Qu'est ce que je fais de plaisance jeanbaptiste (prospect)? Il est porté chez webportage, a facturé fin 2014 sur webportage, dois je le laissé associé (le prospect scx) à ce porté (webportage) ? ou le dissocier ?
    Guillaume durand, à priori je devrais le dissocier, mais je préfère avoir confirmation

    pour plaisance il ne faut pas l'associer car il est prospect sur SC et pas encore porté sur SC. On ne tient pas compte de sa "vie" de porté sur WP.
    idem durand doit avoir son existance sur WP et une autre sur SC

**Comment by MichaelAntoine** [comment]
vu avec @SandraGAZZA 
Il ne faut pas associer un prospect à un porté s'il ne sont pas sur la mm marque
exemple :
Qu'est ce que je fais de plaisance jeanbaptiste (prospect)? Il est porté chez webportage, a facturé fin 2014 sur webportage, dois je le laissé associé (le prospect scx) à ce porté (webportage) ? ou le dissocier ?
Guillaume durand, à priori je devrais le dissocier, mais je préfère avoir confirmation
pour plaisance il ne faut pas l'associer car il est prospect sur SC et pas encore porté sur SC. On ne tient pas compte de sa "vie" de porté sur WP.
idem durand doit avoir son existance sur WP et une autre sur SC

**Comment by MichaelAntoine** [comment]
@mariefranceupnbiz : 
Michael AntoineSandra Gazza
Traiter dans le https://si-upnbiz.atlassian.net/browse/UNBAPI-60
Script SQL : api/database/updates/20150310-update-prospect.sql a executer lors de la mise en prod et recette

pret pour tests
